version: 2.1
orbs:
  win: circleci/windows@2.2.0
  # node: circleci/node@3.0.0
jobs:
  build:
    executor:
      name: win/default
      size: "medium"
    steps:
      - checkout
      - run: npm run build
  test:
    executor:
      name: win/default
      size: "medium"
    steps:
      - checkout
      - run: npm run test
workflows:
  node-tests:
    jobs:
      - test
      - build
