version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          name: Test
          command: npm run test
      - store_artifacts:
          path: coverage
          destination: coverage
      - store_test_results:
          path: test-results.xml

  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          name: Build
          command: npm run build
workflows:
  node-tests:
    jobs:
      - build
      - test
